# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-28 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('release_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genres', models.ManyToManyField(to='flixterix_api_app.Genre')),
                ('release_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flixterix_api_app.Date')),
            ],
        ),
    ]
