# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-28 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixterix_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_year',
            new_name='date',
        ),
    ]
