# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixterix_api_app', '0002_auto_20170528_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='release_year',
            field=models.CharField(max_length=4),
        ),
    ]
