# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-28 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixterix_api_app', '0003_auto_20170528_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
