# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-29 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixterix_api_app', '0006_auto_20170529_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='release_year',
            field=models.DateTimeField(max_length=4),
        ),
    ]
